import { DemoScenario, Dispute, LedgerRecord, AgentTrace } from '../types';

export const DEMO_SCENARIOS: DemoScenario[] = [
  {
    id: 'SCENARIO_A',
    name: '₹25,000 Failed Merchant UPI (Slide 3 PPT)',
    tag: 'Asymmetric UPI Drop',
    category: 'UPI_FAILED',
    amount: 25000,
    bank: 'State Bank of India',
    merchant: 'MegaRetail Pvt Ltd',
    utr: 'UTR9832482348',
    complaint: '₹25,000 was debited from my SBI account to buy an iPad from MegaRetail, but the store says payment failed and merchant never received funds.',
    receiptName: 'sbi_gpay_receipt_25000.jpg',
    receiptUrl: 'https://images.unsplash.com/photo-1554224155-8d04cb21cd6c?auto=format&fit=crop&q=80&w=400',
    ocrConfidence: 98.6,
    expectedOutcome: 'AUTO_RESOLVED',
    description: 'Payer debited, NPCI U69 beneficiary switch timeout, merchant unpaid. Autonomous RBI T+1 reversal order generated.',
  },
  {
    id: 'SCENARIO_B',
    name: '₹80,000 Suspected Fraud (HITL Intercept)',
    tag: 'Safety Gate Tripped',
    category: 'FRAUD_HITL',
    amount: 80000,
    bank: 'HDFC Bank',
    merchant: 'CryptoPay Global Escrow',
    utr: 'UTR7719204812',
    complaint: '₹80,000 unauthorized debit at 3:18 AM from my HDFC salary account. I never shared any OTP or initiated this wire transfer.',
    receiptName: 'hdfc_unauthorized_alert.png',
    receiptUrl: 'https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&q=80&w=400',
    ocrConfidence: 99.1,
    expectedOutcome: 'HITL_ESCALATED',
    description: 'High financial exposure (>₹50,000) & SIM-swap geolocation anomaly drops confidence to 54%. Graph halts at Ombudsman Gate.',
  },
  {
    id: 'SCENARIO_C',
    name: '₹18,500 Delayed Pension / CPPC Branch Merger',
    tag: 'Cyclic Re-Planner',
    category: 'PENSION_DELAY',
    amount: 18500,
    bank: 'Punjab National Bank',
    merchant: 'Central Pension Processing Cell',
    utr: 'UTR4490182741',
    complaint: 'My September pension of ₹18,500 has not arrived in PNB account after branch merger and IFSC migration.',
    receiptName: 'pnb_passbook_extract.png',
    receiptUrl: 'https://images.unsplash.com/photo-1554224154-26032ffc0d07?auto=format&fit=crop&q=80&w=400',
    ocrConfidence: 97.4,
    expectedOutcome: 'REPLAN_RESOLVED',
    description: 'Initial CBS probe times out. Dynamic replanner initiates retry loop, discovers legacy IFSC mismatch, and re-routes credit.',
  },
];

export const SCENARIO_DATA: Record<string, {
  dispute: Dispute;
  ledgers: LedgerRecord[];
  traces: AgentTrace[];
}> = {
  SCENARIO_A: {
    dispute: {
      dispute_id: 'GRV-2026-9921',
      citizen_name: 'Vaidik Lahoria',
      citizen_contact: '+91 98765 43210',
      complaint_text: '₹25,000 was debited from my SBI account to buy an iPad from MegaRetail, but the store says payment failed.',
      status: 'RESOLVED',
      domain: 'DIGITAL_PAYMENTS_UPI',
      claimed_amount: 25000,
      confidence_score: 0.95,
      conflict_detected: true,
      conflict_details: 'Root Cause: Asymmetric Network Partition. Payer bank (SBI) successfully debited ₹25,000, but NPCI Switch reported U69 (Beneficiary Bank Timeout). Merchant PG never received credit. Funds are stranded in NPCI settlement transit pool.',
      requires_human_escalation: false,
      extracted_entities: {
        claimed_amount: 25000,
        utr: 'UTR9832482348',
        txn_id: 'TXN25000',
        payer_bank: 'State Bank of India',
        merchant_name: 'MegaRetail Pvt Ltd',
        date: '2026-09-24T14:10:02Z',
      },
      final_resolution: {
        verdict: 'FAVOR_CITIZEN_AUTO_REVERSAL',
        actionable_order: 'DIRECTIVE: Instruct State Bank of India to execute an unconditional automated credit reversal of ₹25,000.00 to citizen Account ending in **9412 within T+1 working day.',
        regulatory_basis: 'RBI Circular DPSS.CO.PD.No.1164/02.12.004/2019-20 (Harmonisation of TAT & Customer Compensation for Failed Transactions)',
        compensation_entitlement: '₹100/day mandatory statutory penalty payable by SBI to citizen for each 24h delay exceeding T+1 TAT.',
        merchant_status: 'EXONERATED_NO_FUNDS_RECEIVED — MegaRetail PG verified zero settlement liability.',
        citizen_summary: 'Your grievance has been validated against NPCI clearing logs. The ₹25,000 debit was caused by an inter-bank switch drop (Code U69). SBI has been legally ordered to credit back your funds.',
        digital_signature: 'SHA256:d8c2e91a0f44bc7190e4f3a76e93e2b9c512a8f89e21df9043210190ab77192a',
        issued_at: '2026-09-26T14:10:05Z',
        settlement_timeline: 'T+1 (By Tomorrow 17:00 IST)',
      },
    },
    ledgers: [
      {
        source: 'BANK_CBS',
        institution_name: 'State Bank of India (CBS Core)',
        txn_id: 'TXN25000',
        amount: 25000,
        status: 'SUCCESS',
        timestamp: '2026-09-24T14:10:02Z',
        utr: 'UTR9832482348',
        narrative: 'UPI/Dr/MegaRetail/TXN25000/9832482348',
        raw_payload: {
          core_ref: 'SBI-CBS-99210-A',
          account_debited: 'XXXX-XXXX-9412',
          response_code: '00_SUCCESS',
          clearing_session: 'CYCLE_02',
        },
      },
      {
        source: 'NPCI_SWITCH',
        institution_name: 'NPCI UPI Inter-Bank Switch',
        txn_id: 'NPCI-SW-9982348',
        amount: 25000,
        status: 'DEEMED_SUCCESS_BENEFICIARY_TIMEOUT',
        timestamp: '2026-09-24T14:10:05Z',
        utr: 'UTR9832482348',
        narrative: 'Inter-Bank Switch Timeout at Beneficiary Ingress Rail',
        raw_payload: {
          switch_status: 'DEEMED_SUCCESS_BENEFICIARY_TIMEOUT',
          response_code: 'U69',
          settlement_cycle: 'CYCLE_20260924_02',
          transit_pool_id: 'POOL_NPCI_ESC_99',
        },
      },
      {
        source: 'MERCHANT_PG',
        institution_name: 'MegaRetail PG (Razorpay/Swiggy Rail)',
        txn_id: 'ORD-9912',
        amount: 0,
        status: 'PAYMENT_NOT_CREDITED',
        timestamp: '2026-09-24T14:15:00Z',
        utr: 'NOT_ASSOCIATED',
        narrative: 'Order auto-cancelled due to payment webhook timeout',
        raw_payload: {
          order_fulfillment: 'CANCELLED_UNPAID',
          amount_received: 0.0,
          webhook_delivered: false,
          gateway_retries: 3,
        },
      },
    ],
    traces: [
      { node_name: 'ingestion', action_type: 'OCR_PARSED', content: 'OCR extracted UTR: UTR9832482348, Amount: ₹25,000, Payer: SBI, Merchant: MegaRetail', latency_ms: 120, status: 'SUCCESS' },
      { node_name: 'domain_router', action_type: 'CLASSIFIED', content: 'Domain categorized as DIGITAL_PAYMENTS_UPI with 98.6% confidence score', latency_ms: 85, status: 'SUCCESS' },
      { node_name: 'dependency_mapper', action_type: 'MAPPED', content: 'Orchestrated parallel probes across 3 ecosystem endpoints: SBI CBS, NPCI Rail, MegaRetail PG', latency_ms: 45, status: 'INFO' },
      { node_name: 'probing_agents', action_type: 'CBS_QUERY', content: 'SBI Core Banking System responded: ₹25,000 debited from A/C **9412 (Status: SUCCESS)', latency_ms: 410, status: 'SUCCESS' },
      { node_name: 'probing_agents', action_type: 'NPCI_QUERY', content: 'NPCI Switch reported U69: Beneficiary Bank Switch Timeout during settlement transit', latency_ms: 505, status: 'WARNING' },
      { node_name: 'probing_agents', action_type: 'PG_QUERY', content: 'MegaRetail Gateway confirms ₹0 received; Order ORD-9912 marked as CANCELLED_UNPAID', latency_ms: 310, status: 'ERROR' },
      { node_name: 'conflict_arbiter', action_type: 'ARBITRATION', content: 'Asymmetric Ledger Discrepancy detected: Payer Debited vs Merchant Unpaid. Money trapped in transit pool.', latency_ms: 95, status: 'WARNING' },
      { node_name: 'synthesizer', action_type: 'ORDER_ISSUED', content: 'Statutory Reversal Order synthesized under RBI DPSS.1164. Mandated T+1 turnaround with ₹100/day penalty.', latency_ms: 180, status: 'SUCCESS' },
    ],
  },

  SCENARIO_B: {
    dispute: {
      dispute_id: 'GRV-2026-8841',
      citizen_name: 'Dr. Priya Raman',
      citizen_contact: '+91 94451 88201',
      complaint_text: '₹80,000 unauthorized debit at 3:18 AM from my HDFC salary account. I never shared any OTP or initiated this wire transfer.',
      status: 'ESCALATED_HITL',
      domain: 'BANKING_FRAUD_CYBER',
      claimed_amount: 80000,
      confidence_score: 0.54,
      conflict_detected: true,
      conflict_details: 'Safety Boundary Alert: Claim of ₹80,000 exceeds ₹50,000 autonomous threshold. Telecom switch logs indicate rapid SIM-swap 14 minutes prior to transaction. 2FA was authenticated, but originating IP (Lagos/Kyiv Proxy) conflicts with resident geolocation (Pune).',
      requires_human_escalation: true,
      escalation_reason: 'Mandatory Human Gate: Financial liability > ₹50,000 with contradictory 2FA vs IP geolocation telemetry. Autonomous execution halted for Ombudsman officer sign-off.',
      extracted_entities: {
        claimed_amount: 80000,
        utr: 'UTR7719204812',
        txn_id: 'TXN80000',
        payer_bank: 'HDFC Bank Ltd',
        merchant_name: 'CryptoPay Global Escrow',
        date: '2026-09-25T03:18:14Z',
      },
      final_resolution: undefined,
    },
    ledgers: [
      {
        source: 'BANK_CBS',
        institution_name: 'HDFC Bank Ltd (Finacle Core)',
        txn_id: 'TXN80000',
        amount: 80000,
        status: 'SUCCESS',
        timestamp: '2026-09-25T03:18:14Z',
        utr: 'UTR7719204812',
        narrative: 'IMPS/Outward/CryptoPay/TXN80000',
        raw_payload: {
          core_ref: 'HDFC-FIN-3381',
          otp_validated: true,
          ip_origin: '185.220.101.42 (Anonymous Proxy)',
          device_fingerprint: 'NEW_MAC_UNKNOWN',
        },
      },
      {
        source: 'NPCI_SWITCH',
        institution_name: 'NPCI IMPS Switch',
        txn_id: 'NPCI-IMPS-88192',
        amount: 80000,
        status: 'SUCCESS',
        timestamp: '2026-09-25T03:18:16Z',
        utr: 'UTR7719204812',
        narrative: 'Immediate Clearing Acknowledged to Beneficiary Rail',
        raw_payload: {
          switch_status: 'SETTLED',
          routing: 'OUTWARD_IMPS_FAST',
          transit_pool_id: 'BENEFICIARY_IMMEDIATE',
        },
      },
      {
        source: 'MERCHANT_PG',
        institution_name: 'CryptoPay Global Escrow',
        txn_id: 'ESCROW-9881',
        amount: 80000,
        status: 'SETTLED',
        timestamp: '2026-09-25T03:18:22Z',
        utr: 'UTR7719204812',
        narrative: 'USDT purchase completed and withdrawal executed to external wallet',
        raw_payload: {
          kyc_level: 'TIER_1_UNVERIFIED',
          withdrawal_tx_hash: '0x889a712...ec41',
          frozen_by_merchant: false,
        },
      },
    ],
    traces: [
      { node_name: 'ingestion', action_type: 'OCR_PARSED', content: 'Extracted high-value transaction alert: ₹80,000 claimed fraudulent debit', latency_ms: 95, status: 'INFO' },
      { node_name: 'domain_router', action_type: 'CLASSIFIED', content: 'Domain classified as BANKING_FRAUD_CYBER. High-risk protocol triggered.', latency_ms: 110, status: 'WARNING' },
      { node_name: 'dependency_mapper', action_type: 'MAPPED', content: 'Targeting HDFC Finacle, NPCI IMPS Rail, CryptoPay Escrow, and Telecom SIM Registry', latency_ms: 60, status: 'INFO' },
      { node_name: 'probing_agents', action_type: 'CBS_QUERY', content: 'HDFC confirms 2FA OTP passed, but flagged new hardware fingerprint from foreign IP', latency_ms: 380, status: 'WARNING' },
      { node_name: 'probing_agents', action_type: 'TELCO_PROBE', content: 'Airtel API reveals SIM-swap event occurred at 03:04 AM (14 mins prior to OTP dispatch)', latency_ms: 290, status: 'ERROR' },
      { node_name: 'conflict_arbiter', action_type: 'CONFIDENCE_DROP', content: 'Conflict Arbiter evaluated confidence at 54% (<80% threshold). Risk exposure exceeds ₹50,000 ceiling.', latency_ms: 130, status: 'ERROR' },
      { node_name: 'hitl_gate', action_type: 'INTERRUPT_ACTIVE', content: 'LangGraph interrupt() triggered. State machine frozen. Action Card rendered on Ombudsman Dashboard.', latency_ms: 40, status: 'WARNING' },
    ],
  },

  SCENARIO_C: {
    dispute: {
      dispute_id: 'GRV-2026-7734',
      citizen_name: 'Rameshwar Dayal (Veteran)',
      citizen_contact: '+91 97112 30948',
      complaint_text: 'My September pension of ₹18,500 has not arrived in PNB account after branch merger and IFSC migration.',
      status: 'RESOLVED',
      domain: 'PENSION_TREASURY_DIRECT',
      claimed_amount: 18500,
      confidence_score: 0.92,
      conflict_detected: true,
      conflict_details: 'IFSC Code Invalidation after OBC / United Bank merger with PNB. Treasury CPPC attempted credit to legacy branch code (PUNB0024000) which was decommissioned. Dynamic Replanner updated routing to new central clearing IFSC (PUNB0189000).',
      requires_human_escalation: false,
      extracted_entities: {
        claimed_amount: 18500,
        utr: 'UTR4490182741',
        payer_bank: 'Central Pension Processing Cell (CPPC)',
        merchant_name: 'Punjab National Bank',
        date: '2026-09-22T10:00:00Z',
      },
      final_resolution: {
        verdict: 'FAVOR_CITIZEN_AUTO_RECONCILE',
        actionable_order: 'DIRECTIVE: Instruct PNB CPPC to map beneficiary PPO #8839210 to modernized unified IFSC PUNB0189000 and push delayed September pension of ₹18,500 with zero interest penalty.',
        regulatory_basis: 'Central Government Pension Rules & RBI Master Direction on Harmonised Pension Disbursements (RBI/2021-22/34)',
        compensation_entitlement: 'Delay compensation of ₹50/day applicable if pension not credited within 48h of automated mapping notification.',
        merchant_status: 'NOT_APPLICABLE — Treasury entity.',
        citizen_summary: 'Your pension was delayed because of the bank branch merger and IFSC update. FinResolve automatically located the old routing slip, updated it to the new branch code, and scheduled your disbursement.',
        digital_signature: 'SHA256:4a88bc91...f82b',
        issued_at: '2026-09-26T14:10:05Z',
        settlement_timeline: 'Immediate Automated ACH Push',
      },
    },
    ledgers: [
      {
        source: 'BANK_CBS',
        institution_name: 'Punjab National Bank (CBS Core)',
        txn_id: 'PNB-MIGRATE-99',
        amount: 18500,
        status: 'FAILED',
        timestamp: '2026-09-22T10:00:00Z',
        narrative: 'Branch Code PUNB0024000 Decommissioned / Merged',
        raw_payload: { reason: 'INVALID_IFSC_MIGRATION', legacy_branch: 'OBC Delhi Cantt' },
      },
      {
        source: 'NPCI_SWITCH',
        institution_name: 'RBI NACH / Treasury Clearing Switch',
        txn_id: 'NACH-TREASURY-019',
        amount: 18500,
        status: 'PENDING',
        timestamp: '2026-09-22T10:00:02Z',
        narrative: 'Mandate queued awaiting valid beneficiary RTGS/NEFT route',
        raw_payload: { nach_batch_id: 'BATCH-2026-SEP-09', retry_count: 2 },
      },
      {
        source: 'MERCHANT_PG',
        institution_name: 'CPPC Defence Pension Vault',
        txn_id: 'PPO-8839210',
        amount: 18500,
        status: 'SUCCESS',
        timestamp: '2026-09-22T09:55:00Z',
        narrative: 'Treasury funds released to inter-bank clearing pool',
        raw_payload: { ppo_number: 'PPO-8839210', disbursal_batch: 'SEP_2026' },
      },
    ],
    traces: [
      { node_name: 'ingestion', action_type: 'OCR_PARSED', content: 'Scanned pension slip: PPO #8839210, Claimed: ₹18,500', latency_ms: 110, status: 'INFO' },
      { node_name: 'domain_router', action_type: 'CLASSIFIED', content: 'Domain identified: PENSION_TREASURY_DIRECT (Confidence 96%)', latency_ms: 90, status: 'SUCCESS' },
      { node_name: 'probing_agents', action_type: 'CBS_PROBE', content: 'PNB Core reported branch code PUNB0024000 decommissioned in consolidation', latency_ms: 450, status: 'ERROR' },
      { node_name: 'replanner', action_type: 'CYCLIC_REPLAN', content: 'Replanner invoked! Executing cyclic fallback to Central Bank IFSC Directory', latency_ms: 160, status: 'WARNING' },
      { node_name: 'probing_agents', action_type: 'RETRY_SUCCEEDED', content: 'Mapped legacy branch code to active target IFSC: PUNB0189000', latency_ms: 220, status: 'SUCCESS' },
      { node_name: 'conflict_arbiter', action_type: 'RESOLVED', content: 'Reconciliation verified. Cleared for automated direct-benefit re-dispatch.', latency_ms: 90, status: 'SUCCESS' },
      { node_name: 'synthesizer', action_type: 'ORDER_ISSUED', content: 'Dispatched automated ACH reroute order to PNB CPPC Cell.', latency_ms: 140, status: 'SUCCESS' },
    ],
  },
};
